trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - src/_drafts
      - README.md

jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 2.7'
      
      - script: |
          gem install jekyll bundler
        displayName: 'install jekyll'
          
      - script: |
          bundle install
          bundle exec jekyll build
        displayName: 'jekyll build'
          
      - task: CopyFiles@2
        displayName: 'Copy files to staging'
        inputs:
          SourceFolder: '_site'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish build artifact'
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: site
    
  - job: deploy
    pool:
      vmImage: 'ubuntu-20.04'
    dependsOn: build
    condition: succeeded()
    steps:
      # download the artifact drop from the previous job
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: site
          downloadPath: '$(System.ArtifactsDirectory)'

      # Copy files to Azure Blob Storage
      - task: AzureCLI@2
        displayName: Copy data to storage account
        inputs:
          azureSubscription: arm-service-connection
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
              az storage blob upload-batch \
                --destination \$web \
                --account-name "strbgvchah" \
                --source "$(System.ArtifactsDirectory)/site"

      # Purge CDN to update content
      - task: AzureCLI@2
        displayName: Purge CDN contents
        inputs:
          azureSubscription: arm-service-connection
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
              az cdn endpoint purge \
              --name rbgv-cdn-chah-avh \
              --profile-name cdn-chah \
              --resource-group SC-CHAH \
              --content-paths '/*'
